language: nodejs
node_js: 12

branches:
  only:
  - gh-pages

install:
  - npm install

script:
  - npm run update-sidebar
  - git status

after_success:
  - echo "Running in a Travis environment, re-attaching git HEAD to ${TRAVIS_BRANCH}"
  - git config --global user.email "travis@travis.ibm.com"
  - git config --global user.name "Travis CI"
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.ibm.com/${TRAVIS_REPO_SLUG}.git
  - git symbolic-ref HEAD "refs/heads/${TRAVIS_BRANCH}"
  - git add .
  - git commit -m "[skip ci] doc update"
  - git push --set-upstream origin gh-pages